### PR TITLE
Fixing IDENTITY-3401

### PR DESCRIPTION
**Pull request by kasungayan**

### CODE REVIEW

**Comment by hasinthaindrajee** [comment]
@kasungayan  - I dont think this fix will be enough. Since no authentication has been taken place before hand there wont be any information in thread locals. Therefore you need to find out correct user realm and then authenticate the user. WDYT ?

**Comment by hasinthaindrajee** [comment]
And these attempts do not get tracked.. You need to authenticate the user first and then update the credentials. (Authentication happnens inside userstore manager. But it does not trigger any listener. so cannot track this event)

**Comment by johannnallathamby** [comment]
Let's do this in the master branch only then, because this is an API change. Since for tenants if we do this change, we are expecting the tenant domain qualified username, which was not the earlier behaviour. Earlier we get the tenant domain from the logged in user's context for the admin service.

**Comment by darshanasbg** [comment]
Need to fix as @hasinthaindrajee mentioned. Created https://wso2.org/jira/browse/IDENTITY-5408 to track this.

**Pull request closed without merging**
